services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prixfetl_backend
    ports:
      #- "127.0.0.1:5011:5000" # port flask en local uniquement
      - "5011:5000"  # Port Flask
      - "2222:22"    # Port SSH
      - "8888:8888"  # Port Jupyter Notebook
    volumes:
      - .:/app
      - ssh_keys:/etc/ssh  # Volume persistant pour les clés SSH
      - ssh_auth:/home/ubuntu/.ssh  # Sauvegarde des clés publiques
      - /home/ubuntu/.vscode-server:/root/.vscode-server
      - ./cron_logs:/var/log
    environment:
      - FLASK_ENV=production
      - FLASK_APP=/app/PrevisionPrix.py
      - POSTGRES_HOST=prixfetl_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=IAFetL
      - POSTGRES_USER=prixfetl
      - POSTGRES_PASSWORD=Leumces123
      - DATA_RAW_DIR=/app/data/raw
      - DATA_OUTPUT_DIR=/app/tests
      - DATA_OUTPUT_PROCESSED_DIR=/app/data/processed
      - API_TOKEN_SECRET=e67d89305f2763bd4920bb0deda2e33467a9154522a99f5a6268e1a222ab9e75
    command: ["/entrypoint.sh"]
    networks:
      - prixfetl_network

  postgres:
    image: postgres:17
    container_name: prixfetl_postgres
    ports:
      - "5012:5432"
    environment:
      POSTGRES_USER: prixfetl
      POSTGRES_PASSWORD: Leumces123
      POSTGRES_DB: IAFetL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prixfetl_network

  articles_api:
    build:
      context: ./articles_api
      dockerfile: Dockerfile
    container_name: articles_api
    ports:
      - "51696:3001"
    volumes:
      - /home/ubuntu/PrixFetL/articles_api/app:/app  # Monte le code source pour édition avec VS Code
    environment:
      - API_KEY=510e8a852dc3ab4a3733e2f7c81cc21cd072f86384311b5fb66e0d7b0e4674ef
      - DATABASE_URL=postgresql://articles_user:Leumces123@prixfetl_postgres:5432/articles
      - UPLOAD_FOLDER=/app/images
      - FTP_URL=ftp.cluster027.hosting.ovh.net
      - FTP_USER=intelln
      - FTP_PASSWORD=JtbNldhKHf5f874kfhl58fdjhgf528

    depends_on:
      - postgres
    networks:
      - prixfetl_network


networks:
  prixfetl_network:
    driver: bridge

volumes:
  ssh_keys:
  ssh_auth:  # Nouveau volume pour /home/ubuntu/.ssh
  python_packages:
  postgres_data:
  cron_logs:
  .vscode-server:
